# Generated by Django 5.0.6 on 2024-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headOfficeCode', models.CharField(default='', max_length=10)),
                ('branchOfficeCode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('headOffice', models.CharField(default='', max_length=100)),
                ('branchOffice', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=250)),
                ('tel', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
